name: Build and Deploy Installer

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: mvn clean package

      - name: Package installer with jpackage
        shell: cmd
        run: |
          mkdir dist
          jpackage ^
          --type exe ^
          --input target ^
          --name XMLUtils-1.0 ^
          --main-jar XMLUtils-1.0-SNAPSHOT.jar ^
          --main-class gg.seraph.main.Editor ^
          --dest dist ^
          --java-options "--enable-preview"
          move dist\XMLUtils-1.0.exe XMLUtils-1.0.exe

      - name: Upload installer artifact
        uses: actions/upload-artifact@v4
        with:
          name: installer
          path: XMLUtils-1.0.exe

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download installer artifact
        uses: actions/download-artifact@v4
        with:
          name: installer

      - name: Show extracted files (debug)
        run: ls -R

      - name: Upload to Windows Server via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.WIN_SERVER_HOST }}
          username: ${{ secrets.WIN_SERVER_USER }}
          password: ${{ secrets.WIN_SERVER_PASS }}
          source: "XMLUtils-1.0.exe"
          target: "C:/inetpub/wwwroot/downloads"
